version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: skyvault_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /Users/sanujaariyapperuma/Documents/Projects/SkyVault/dockerdbvolume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: skyvault_db
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
